"""Build the bounded, generated HOT memory view from the structured store."""
from __future__ import annotations

import json
import re
import tomllib
import threading
from datetime import date
from pathlib import Path

from . import ROOT, bus, memory_store

BUILD_LOCK = threading.Lock()


def fresh(root=ROOT):
    """A view is fresh only when both files exist and HOT is at least as new."""
    directory = Path(root) / ".orchestrator" / "memory"
    try:
        return (directory / "HOT.md").stat().st_mtime_ns >= (directory / "index.sqlite").stat().st_mtime_ns
    except OSError:
        return False

HEADER = "# Generated by memory_hot; do not edit."
OPEN_STATUSES = {"queued", "held", "running"}
KIND_WEIGHTS = {
    "gotcha": 3, "decision": 2, "architecture": 2, "model_note": 1,
    "retrospective": 1, "strategy": 1, "skill_outcome": 1, "reference": 1,
}


def _config(root):
    path = Path(root) / ".orchestrator" / "pool.toml"
    with path.open("rb") as handle:
        return tomllib.load(handle).get("memory", {})


def _tasks(root):
    """Take one immutable snapshot of bus tasks for both pinning and scoring."""
    result = {}
    task_dir = Path(root) / ".orchestrator" / "tasks"
    for path in sorted(task_dir.glob("*.json")) if task_dir.exists() else ():
        task_id = path.stem
        try:
            if Path(root).resolve() == Path(ROOT).resolve():
                task = bus.get(task_id)
            else:
                task = json.loads(path.read_text())
        except (KeyError, FileNotFoundError, json.JSONDecodeError):
            continue
        if task.get("status") in OPEN_STATUSES:
            result[task_id] = task
    return result


def _configured_pin(record, rules):
    for rule in rules:
        if rule == "architecture" and record["kind"] == "architecture":
            return True
        if rule == "gotcha:open" and record["kind"] == "gotcha":
            outcome = record.get("outcome", "")
            if not outcome.strip() or re.search(r"\b(?:unresolved|open)\b", outcome, re.I):
                return True
        if rule.startswith("decision:") and record["kind"] == "decision":
            if rule.split(":", 1)[1] in record.get("tags", []):
                return True
    return False


def _task_mentions(record, task):
    title_tokens = set(re.findall(r"\w+", str(task.get("title", "")).lower()))
    scope = task.get("scope") or task.get("write_scope") or []
    if isinstance(scope, str):
        scope = [scope]
    scope_tokens = {Path(str(item)).stem.lower() for item in scope}
    return any(str(component).lower() in title_tokens | scope_tokens
               for component in record.get("components", []))


def _score(record, recent_days, open_tasks):
    try:
        age = max(0, (date.today() - date.fromisoformat(record["date"])).days)
        recency = max(0.0, 1.0 - age / max(1, recent_days))
    except (TypeError, ValueError):
        recency = 0.0
    mentions = sum(_task_mentions(record, task) for task in open_tasks.values())
    return recency + KIND_WEIGHTS.get(record["kind"], 0) + mentions


def _line(record):
    line = f"- {record['date']} | {record['kind']} | {record['title']}"
    skill = next((tag.split(":", 1)[1] for tag in record.get("tags", [])
                  if tag.startswith("skill:")), None)
    if skill:
        return line + f" | learned skill: {skill}"
    if record["kind"] == "gotcha" and record.get("body"):
        sentence = re.split(r"(?<=[.!?])(?:\s+|$)", record["body"].strip(), maxsplit=1)[0]
        line += f" | {sentence}"
    return line


def _tokens(text):
    return (len(text) + 3) // 4


def build(root=ROOT, budget_tokens=None):
    with BUILD_LOCK:
        return _build(root, budget_tokens)


def _build(root=ROOT, budget_tokens=None):
    root = Path(root)
    cfg = _config(root)
    budget = int(budget_tokens if budget_tokens is not None else cfg.get("hot_budget_tokens", 3000))
    recent_days = int(cfg.get("hot_recent_days", 14))
    rules = cfg.get("hot_never_compact", [])
    records = memory_store.all_records(root, tier="warm") + memory_store.all_records(root, tier="hot")
    records = list({record["id"]: record for record in records}.values())
    open_tasks = _tasks(root)
    pinned = [r for r in records if _configured_pin(r, rules)
              or any(task_id in open_tasks for task_id in r.get("source_tasks", []))]
    pinned_ids = {r["id"] for r in pinned}
    ranked = sorted((r for r in records if r["id"] not in pinned_ids),
                    key=lambda r: (-_score(r, recent_days, open_tasks), r["date"], r["id"]))
    chosen = sorted(pinned, key=lambda r: (r["date"], r["id"]), reverse=True)

    def rendered(selected):
        selected_ids = {record["id"] for record in selected}
        dropped_decisions = [record for record in records
                             if record["id"] not in selected_ids and record["kind"] == "decision"
                             and "governing" in record.get("tags", [])]
        lines = [HEADER, "", *(_line(record) for record in selected)]
        for record in sorted(dropped_decisions, key=lambda r: r["id"]):
            lines.append(f"memory show {record['id']}")
        return "\n".join(lines).rstrip() + "\n"

    for record in ranked:
        candidate = chosen + [record]
        if _tokens(rendered(candidate)) <= budget:
            chosen.append(record)
    chosen.sort(key=lambda r: (r["date"], r["id"]), reverse=True)
    text = rendered(chosen)
    chosen_ids = {record["id"] for record in chosen}
    dropped = sorted(record["id"] for record in records if record["id"] not in chosen_ids)
    tiers = {record["id"]: ("hot" if record["id"] in chosen_ids else "warm") for record in records}
    memory_store.set_tiers(tiers, root)
    output = root / ".orchestrator" / "memory" / "HOT.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    return {"records": chosen, "tokens": _tokens(text), "dropped": dropped,
            "pinned": sorted(pinned_ids), "over_budget": _tokens(text) > budget, "view": text}


def compact(root=ROOT):
    return build(root)
